### ISSUE TITLE
Problema de autodescarga continua

### ISSUE THREAD

**Issue by Khalel-Albus** [laplaces-entropy/R-TMOLoader#1]
Bro de verdad excelente proyecto, mucho mejor que el RipSM Chronium la verdad porque no jala casi recursos y es igual de util, sería genial que tuviese la opción de multidescarga pero bueno, es un proyecto en construcción.

Mi problema es el siguiente, cuando abro la aplicacion aparece la alerta de actualización falsa para anunciar lo sucedido en el scan y la borrada de tu cuenta, el inconveniente es que entiendo que se descargue una nueva version y todo pero cada vez que abro la nueva versión descargada me hace lo mismo y termina descargando la misma que estaba usando, y eso lo hace infinitamente cada vez que lo abro, por ende ya tengo como 7 versiones de la misma app 🤷‍♂️ quisiera que pudieses reparar dicho error ya que bueno trabajo con conexión limitada y pierdo 8 mb cada que abro la app, quiza no sea mucho pero a la suma de las veces que la abra me deja sin saldo, dicho esto felicidades por hacer algo tan util y ligero como esto, te deseo suerte con el proyecto!

Adjunto par de capturas para que observes lo que me sucede.
![Captura de pantalla (147)](https://user-images.githubusercontent.com/64998540/81362987-26ee0b80-90b0-11ea-8cd9-7357aaf00186.png)
![Captura de pantalla (146)](https://user-images.githubusercontent.com/64998540/81362990-28b7cf00-90b0-11ea-878d-9e181562ff28.png)

**Comment by laplaces-entropy** [comment]
Uy, eso no debería pasar, olvide cambiar una línea de código que prevenia que eso ocurriera, mañana o en un rato lo reparo, perdón por el error, Gracias por la paciencia.
Respecto a la multidescarga, no sé si sea muy buena idea, pero puedo inténtalo... Estás 2 semanas no podré actualizar demasiado, pido paciencia para continuar descarga. En cuanto a la interfaz... Pues tengo mucho por delante...

**Comment by laplaces-entropy** [comment]
Me equivoqué perdón por esos mensajes XD

**Comment by Khalel-Albus** [comment]
Tranquilo son cosas que pasan y apenas está en desarrollo la aplicación, agradezco al menos poder tener con que bajar las historietas que quiera.
 En cuanto a lo del multidescargas no soy nada entendido con la programación pero si el problema es que tmo detecte mas de una conexión en una misma ip por que no poner un margen de 10 segundos u 8 en caso de que sirva entre descarga y descarga? así daría tiempo de que el servidor lo reconozca como una nueva entrada real, eso ahorraría el tener que esperar a que se descargue un archivo para comenzar con otro, algo así como una cola de descargas tipo IDM, por la interfáz no me preocupo, despues de todo lo que mas importa es la funcionalidad, en mi ignorancia pregunto, hay alguna forma de extraer los enlaces de tmo sin entrar a los capitulos? porque esta app baja toda la historieta si le pones el enlace raiz de la misma, pero para los que andamos un poco avanzados en alguna historia es un poco tedioso ir sacando enlace por enlace (ni RipSM tenía esa opción) espero que mis sugerencias sean útiles y espero no meter mas presión a tu tarea de desarrollador, las hago con intención de mejorar este proyecto que me agrada bastante, gracias por tomar en cuenta lo que he dicho, espero con ansias el avance de esta app que promete ser muy bueno!

**Comment by laplaces-entropy** [comment]
Supongo que puedo, pero de nuevo, pido paciencia por estás 2 semanas, en un rato más parcho el error.

**Comment by laplaces-entropy** [comment]
Ya repare el error. Si tienes otra sugerencia o error crea otro Issue con ella. Gracias

**Comment by Khalel-Albus** [comment]
No hay presiones, gracias a ti por esta excelente herramienta, lo que puedas lograr es bueno, igual la publicare por fb para que más personas le den uso.

**Comment by laplaces-entropy** [comment]
Gracias, aunque sinceramente no creo que mucha gente le atraiga la pantalla negra por ahora, pero bueno, si a alguien le sirve me conformo
