### ISSUE TITLE
AVISO

### ISSUE THREAD

**Issue by laplaces-entropy** [laplaces-entropy/R-TMOLoader#10]
Hola, he estado pensando en el tema de la interfaz, pero la verdad es que no estoy muy convencido, para empezar creo que tal vez estoy cometiendo algunos errores en la forma de programar, por lo que creo que voy a hacer una re escritura completa (Probablemente, pero tal vez solo le de una revisión completa), ademas de investigar un poco mejor el funcionamiento completo de lo que uso.
No quiero hacer una interfaz con un programa mal hecho porque eso implicaría que el programa falle mucho. Por tanto, tengo que avisar que posiblemente no actualice durante un tiempo. Sobre los errores que ya hay (#9 , #7), puesto que creo que se deben a TMO en si, no los reparare a menos que pueda identificar la causa exacta del error, pero esto es complicado porque solo falla cuando la pagina falla. Los "tutoriales", los hare, pero pido un poco de paciencia.

**Comment by laplaces-entropy** [comment]
Por cierto, si alguien quiere alguna cambio, avise por aqui.

**Comment by Khalel-Albus** [comment]
Por acá de nuevo yo, siempre reportando bugs pero ahora me da con todos los enlaces raiz, cuando pongo el root de algun manga de TMO, se cierra sola la app, pensé en un inicio que era solo con Torre de dios porque ya en el pasado la mayoria de los errores me los dada con dicho manhwa, pero he intentado con varios mangas y el error es igual, le doy enter sale un error pero se tranca la interfaz antes de poder leer algo, tomé una cap pero no se si se distingue el error, otro error es que cuando si funcionaban los enlaces raiz el "desde" a veces no funcionaba y empezaba a descargar desde el principio, pero solo era a veces como no me resulto una graaan molestia no lo reporté pero que no lea los enlaces raiz me lleva al mismo punto por el que sugerí o un extractor de enlaces, cuando se esta avanzado en la historia estan entrando pagina por pagina a los enlaces es tan tedioso que es preferible leerlo online (lo cual no es lo que quiero)

por cierto como añadido especial un amigo me dijo que podría intentar hacerte la interfaz, pero necesita saber con que lenguaje trabajas, por los primeros iconos de la app supuse que pyton pero ni idea, sería bueno saber a ver si el puede hacerlo o ayudarte con eso. sin mas que decir buenas noches!
![image](https://user-images.githubusercontent.com/64998540/87380315-3a11d180-c560-11ea-8c46-6a6ba9c1e685.png)

**Comment by laplaces-entropy** [comment]
Hola! Note el error de los enlaces de raíz hace unos 3 días, estoy investigando, pero lo más probable es que sea por un cambio en TMO. Suponiendo que me ponga en ello, debería ser relativamente fácil de resolver. Sobre lo de la GUI... Si, trabajo sobre Python 3, en realidad he tenido oportunidad de hacer la interfaz, pero tenía la esperanza de algún día poder usar esto en Android (es donde más leo manga), para eso se necesitaba una librería que soportará multiplataforma; pero creo que excede mis capacidades al menos por ahora. Si creen que pueden contribuir sería de gran ayuda (Con o sin posible soporte para Android)... El problema es el código, me preocupa publicarlo y que sea parcheado... Por favor creen un issue para hablar sobre esto y ver cómo contactarnos.

Pd. Dices reportando Bugs como algo malo, agradezco mucho el que se reporten errores, significa que alguien usa mi trabajo, y el reparar errores implica mejorar el programa. Entre más se reporte y sugiera, creo que es mejor.

**Comment by laplaces-entropy** [comment]
Por cierto, si quieres ver el error fácilmente y no quieres que se cierre puedes abrirlo desde cmd o Powershell

**Comment by laplaces-entropy** [comment]
La version [1.3.0](https://github.com/laplaces-entropy/R-TMOLoader/releases/tag/v1.3.0) repara lo que mencionaba en este issue, cierro
