### ISSUE TITLE
Multidescarga?

### ISSUE THREAD

**Issue by laplaces-entropy** [laplaces-entropy/R-TMOLoader#2]
Tengo que probarlo...

**Comment by Khalel-Albus** [comment]
Lo probaste?

**Comment by laplaces-entropy** [comment]
> Lo probaste?

Jeje, tareas y otros proyectos (En este ámbito tambien : D)... pero no, estoy probando de manera externa la forma de crear otros procesos, pero no se si sea muy factible hacerlo con lo que se hasta ahora...

Perdon

**Comment by laplaces-entropy** [comment]
Por fin di con una forma factible de hacerlo. Falta implementarlo de manera completa

**Comment by laplaces-entropy** [comment]
Listo!, se pueden configurar el numero de 'thread' (Hilos) o procesos de descarga simultáneos. Según Task manager y lo que recuerdo, la memoria RAM necesaria subió un poco (Como 5 - 10 MB), el consumo de CPU sube en función de los procesos y la red también. El consumo de ancho de banda es considerable.

**Comment by Khalel-Albus** [comment]
genial! actualizaré para probar! bueno el uso de ram es super bajo (a menos que sea como el ram tief google chrome no cuenta como consumo alto) otra cosa, estuve experimentando y descargando de 2 instancia del programa al mismo tiempo y me fue super bien, con esta mejora estará todo mucho mas cómodo, gracias!

**Comment by laplaces-entropy** [comment]
> genial! actualizaré para probar! bueno el uso de ram es super bajo (a menos que sea como el ram tief google chrome no cuenta como consumo alto) otra cosa, estuve experimentando y descargando de 2 instancia del programa al mismo tiempo y me fue super bien, con esta mejora estará todo mucho mas cómodo, gracias!

... Aun no se ha actualizado xD, lo actualizare hoy en la noche
