### ISSUE TITLE
Cierres inesperados

### ISSUE THREAD

**Issue by laplaces-entropy** [laplaces-entropy/R-TMOLoader#7]
Si TMO esta muy lento, la aplicación puede tener un error y cerrarse a media descarga,

**Comment by mirage548** [comment]
alguna tutorial de como descargar de capitulos especificos?
ejemplo: pego el url del manda y el software me dice desde: *que coloco aca?*

**Comment by laplaces-entropy** [comment]
@mirage548 
> alguna tutorial de como descargar de capitulos especificos?
> ejemplo: pego el url del manda y el software me dice desde: *que coloco aca?*

Hola, no xD, perdón por no hacer tutorial, pero he estado ocupado con tareas, de hecho recorte un poco la actualización para sacarla más rápido.
Para descargar desde un capítulo específico, escribe el número de capitulo, es decir, ingresas la URL del manga / manhua / manwha y despues, dónde pregunta '¿DESDE?', escribe el número (Ej. 3.20).
Es importante incluir todas las décimas o ceros.
Perdón por no responder rápido. También, por favor, para preguntar algo o reportar un error, abre un nuevo Issue. Gracias

**Comment by laplaces-entropy** [comment]
No estoy muy seguro de si esto se soluciono o no con lo que agregue, pero por lo menos creo que baja la posibilidad de que ocurra.

**Comment by Khalel-Albus** [comment]
pregunta! para cuando estaría lista la nueva version? veo que aun está en progreso y la version que uso (1.2.0) sigue con el fallo de cierre inmediato cuando coloco un enlace raíz, hasta ahora sigo como en el inicio, copiando url por url cada cap de historieta para introducirla manual, el "DESDE" me había facilitado muchisimo todo y era suuuuuper comodo, disculpa mi impaciencia es que estoy viciado con una serie y quiero seguir bajandola pero a bajo costo de internet (no tengo wifi F) xD

**Comment by laplaces-entropy** [comment]
Hoy en la noche :/, quiero verificar que todo funcione, si quieres ver exactamente lo que hago y termino, puedes verlo en la pestaña de Projects
